num_iterations: 1     # iterations for each config
starting_iteration: 0 # start id of iteration
exp_id: CL_KAN_1D        # id of current run
logs_dir: logs        # dir for logs
report_interval: 5    # report interval

# dataset specification
dataset:
  name: Oracle # name in [WiSig, LoRa, Drones]
  config:
    file: data_256_62ft.h5     # file path for WiSig
    k_fold:             # specification for k_fold
      total_devices: 16
      ratio: 5
    modality: raw_iq
    #selected_receivers: !!python/tuple [0,]
    test_config:
      #days: !!python/tuple [0,1,2,3]
      type: validation
    train_config:
      #days: !!python/tuple [0,1,2,3]
      type: train

# train and test loaders
train_loader:
  num_workers: 3
  batch_size: 128
  shuffle: true

test_loader:
  num_workers: 3
  batch_size: 128
  shuffle: false

# specifications for metrics computing
evaluation:
  clusters_numbers: !!python/tuple [200] # for which numbers of clusters calculate metrics

# specifications for approach and trainer parameters
approach:
  name: Sim_CLR
  
  config:
    device: cuda
    num_epochs: 100
    large_augs: False
    augs_type: static
    clusters_loss: False
    
  trainer:
    mlp_head:
        in_features: 20
        out_features: 20

    augmentations:
      dims: 1
      viewmaker_config:
        in_channels: 2
        singal_length: 256
        prob: 0.5
        noise_std: 0.05
      
    main_optimizer:
      name: Adam
      config:
        lr: 0.0001
    augs_optimizer:
      name: Adam
      config:
        lr: 0.0001

# specifications for feature_extractor
feature_extractor:
  name: KANS_Encoder
  config:
    input_size: 512
    hidden_size: 20

#feature_extractor:
#  name: Simple_CNN_1D
#  config:
#    input_signal_length: 256
#    in_channels: 2
#    features_size; 20

