num_iterations: 1     # iterations for each config
starting_iteration: 0 # start id of iteration
exp_id: DC_KAN_1D        # id of current run
logs_dir: logs        # dir for logs
report_interval: 5    # report interval
starting_fold: 0
# dataset specification
dataset:
  name: WiSig
  config:
    file:  ManySig.pkl
    k_fold: 
      total_devices: 6
      ratio: 6
    selected_receivers: !!python/tuple [0,]
    test_config:
      type: validation
    train_config:
      type: train

# train and test loaders
train_loader:
  num_workers: 10
  batch_size: 128
  shuffle: true

test_loader:
  num_workers: 10
  batch_size: 128
  shuffle: false

# specifications for metrics computing
evaluation:
  clusters_numbers: !!python/tuple [80,] # for which numbers of clusters calculate metrics

# specifications for approach and trainer parameters
approach:
  name: Deep Clustering
  config:
    clusters_update_interval: 20
    n_clusters: 20
    device: cuda
    num_epochs: 40
  trainer:
    main_optimizer:
      name: Adam
      config:
        lr: 0.001 # ranges are supported

# specifications for feature_extractor
feature_extractor:
  name: KANS_Encoder
  config:
    input_size: 512
    hidden_size: 20
    n_classes: 20

#feature_extractor:
#  name: Simple_CNN_1D
#  config:
#    input_signal_length: 256  
#    in_channels: 2
#    features_size; 20
#    n_classes: 20